"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "hi";

interface LanguageContextType {
    language: Language;
    toggleLanguage: () => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
    en: {
        "header.title": "Government of India",
        "header.subtitle": "Ministry of Electronics & IT",
        "search.placeholder": "Search services or track application...",
        "nav.home": "Home",
        "nav.about": "About Us",
        "nav.login": "Login",
        "nav.register": "Register",
        "nav.logout": "Logout",
        "nav.media": "Media",
        "nav.contact": "Contact",
        "nav.projects": "Projects",
        "nav.dashboard": "Dashboard",
        "home.hero.title": "Apply for Government Documents",
        "home.hero.title.highlight.0": "Faster than ever",
        "home.hero.title.highlight.1": "Without visiting office",
        "home.hero.title.highlight.2": "Without paperwork",
        "home.hero.title.highlight.3": "With the power of AI",
        "home.hero.subtitle": "Official portal for citizen services. Upload proofs securely and let AI help you with government paperwork.",
        "home.btn.start": "Apply Now",
        "home.btn.learn": "How it Works",
        "home.pill.0": "Digital India Initiative",
        "home.pill.1": "Empowering Citizens",
        "home.pill.2": "Minimum Government, Maximum Governance",
        "home.pill.3": "Paperless, Faceless, Cashless",
        "home.feature.verify": "Aadhaar Verification",
        "home.feature.verify.desc": "Secure identity authentication using UIDAI standards.",
        "home.feature.autofill": "AI Assistant",
        "home.feature.autofill.desc": "Voice-enabled form filling in multiple Indian languages.",
        "home.feature.instant": "DigiLocker Integration",
        "home.feature.instant.desc": "Issued documents available instantly in your DigiLocker.",
        "home.select.title": "Select Citizen Service",
        "home.select.subtitle": "Choose the ministry service you wish to apply for.",
        "footer.about": "About this Portal",
        "footer.desc": "An initiative by Government of India to simplify citizen services through Artificial Intelligence.",
        "footer.links": "Government Links",
        "footer.contact": "Contact Details",
        "footer.rights": "Government of India. All Rights Reserved.",
        "upload.title": "Upload Required Documents",
        "upload.desc": "Securely upload proofs for validation.",
        "upload.secure.title": "Secure Upload",
        "upload.secure.desc": "Your documents are encrypted and processed securely. No data is stored permanently without your consent.",
        "upload.optional.title": "Optional",
        "upload.optional.desc": "Documents help auto-fill fields, but you can skip and proceed to manual entry if preferred.",
        "upload.doc.aadhaar": "Aadhaar Card",
        "upload.doc.pan": "PAN Card",
        "upload.doc.income": "Income Proof",
        "upload.instr.aadhaar": "Upload both sides (front & back) or a single PDF",
        "upload.instr.generic": "Upload clear image or PDF",
        "upload.btn.back": "Get Started",
        "upload.btn.skip": "Skip & Fill Manually",
        "how.title": "How it Works",
        "how.subtitle": "Simple 4-step process to get your government certificates.",
        "how.step1.title": "Upload Documents",
        "how.step1.desc": "Securely upload your Aadhaar, PAN, or other required IDs.",
        "how.step2.title": "AI Extraction",
        "how.step2.desc": "Our system automatically reads details from your documents.",
        "how.step3.title": "Form Auto-fill",
        "how.step3.desc": "Review the pre-filled application form for accuracy.",
        "how.step4.title": "Instant Download",
        "how.step4.desc": "Get your digitally signed certificate instantly.",
        "step.1": "Select Service",
        "step.2": "Upload Documents",
        "step.3": "Review Form",
        "step.4": "Done",
        "upload.drag": "Click to Upload Document",
        "upload.drag.sub": "SVG, PNG, JPG or PDF (max. 10MB)",
        "upload.processing": "Processing...",
        "upload.success": "File Uploaded Successfully",
        "upload.instr.title": "Important Instructions",
        "upload.instr.1": "Option 1: Upload a single document with both sides (front & back).",
        "upload.instr.2": "Option 2: Upload 2 separate photos (front & back).",
        "upload.instr.generic.1": "Ensure text is clear and readable.",
        "upload.instr.generic.2": "File size must not exceed 10MB.",
        "dashboard.title": "User Dashboard",
        "dashboard.subtitle": "Manage your digital identity and documents.",
        "dashboard.signout": "Sign Out",
        "dashboard.verified": "Verified Account",
        "dashboard.active_apps": "Active Applications",
        "dashboard.saved_fields": "Saved Profile Fields",
        "dashboard.locker.title": "My Digital Locker",
        "dashboard.locker.subtitle": "Data automatically extracted from documents",
        "dashboard.field": "Field Name",
        "dashboard.value": "Value",
        "dashboard.source": "Source",
        "dashboard.actions": "Actions",
        "dashboard.locker.empty": "No data stored yet. Upload documents to auto-populate your locker.",
        "dashboard.recent.title": "Recent Activity",
        "dashboard.recent.empty": "No recent applications found. Start a new application on the Home page!",
        "dashboard.apply": "Apply Now",
        "dashboard.delete.confirm": "Are you sure you want to delete this activity?",
        "dashboard.delete.fail": "Failed to delete application",
        "dashboard.update.fail": "Failed to update profile",
        "in_progress": "In Progress",
        "completed": "Completed",
        "nav.profile": "Profile Fields",
        "nav.applications": "Applications",
        "nav.services": "Services",
        "nav.settings": "Settings",
        "about.title": "About Us",
        "about.mission": "Our Mission",
        "about.mission.desc": "To empower citizens by providing seamless, transparent, and efficient digital services. We aim to bridge the digital divide and ensure that government benefits reach the last mile with ease and dignity.",
        "about.vision": "Vision",
        "about.vision.desc": "Transforming India into a digitally empowered society and knowledge economy by focusing on digital access, inclusion, and empowerment.",
        "about.values": "Core Values",
        "about.value.1": "Transparency & Integrity",
        "about.value.2": "Citizen-Centricity",
        "about.value.3": "Innovation & Excellence",
        "about.value.4": "Inclusivity",
        "about.who": "Who We Are",
        "about.who.desc1": "The Ministry of Electronics and Information Technology (MeitY) stands as a pillar of India's technological evolution. We are committed to fostering a thriving ecosystem for digital innovation, cybersecurity, and e-governance.",
        "about.who.desc2": "Our platform integrates various services to streamline administrative processes, reducing paperwork and enhancing the ease of living for every citizen.",
        "services.title": "Citizen Services",
        "services.subtitle": "Accessible, Transparent, and Efficient Government Services for All.",
        "service.cert.title": "Digital Certificates",
        "service.cert.desc": "Apply for Birth, Caste, Income, and Domicile certificates online.",
        "service.empl.title": "Employment Exchange",
        "service.empl.desc": "Register for job opportunities and unemployment assistance.",
        "service.health.title": "Health Services",
        "service.health.desc": "Access telemedicine, hospital appointments, and health records.",
        "service.edu.title": "Education & Scholarships",
        "service.edu.desc": "Apply for scholarships and view examination results.",
        "service.land.title": "Land Records",
        "service.land.desc": "View and verify land ownership details and property maps.",
        "service.util.title": "Utility Payments",
        "service.util.desc": "Pay electricity, water, and gas bills seamlessly.",
        "service.award.title": "Awards & Recognitions",
        "service.award.desc": "Nominations for Padma Awards and other state honors.",
        "service.trans.title": "Transport Services",
        "service.trans.desc": "License renewal, vehicle registration, and challan payments.",
        "projects.title": "Major Initiatives",
        "projects.subtitle": "Transforming the nation through key projects.",
        "project.di.title": "Digital India",
        "project.di.desc": "A flagship programme to transform India into a digitally empowered society and knowledge economy.",
        "project.di.status": "Ongoing",
        "project.sc.title": "Smart Cities Mission",
        "project.sc.desc": "An urban renewal and retrofitting program by the Government of India with the mission to develop smart cities.",
        "project.sc.status": "Phase 2",
        "project.bn.title": "BharatNet",
        "project.bn.desc": "The world's largest rural broadband connectivity programme using Optical Fibre.",
        "project.bn.status": "Completed",
        "media.title": "Media Center",
        "media.latest": "Latest Press Releases",
        "media.gallery": "Photo Gallery",
        "media.view_all": "View All Photos",


        "media.pr.1.date": "Nov 14, 2025",
        "media.pr.1.title": "Digital Personal Data Protection Rules, 2025 Notified",
        "media.pr.1.desc": "The Government of India has officially notified the DPDP Rules 2025, operationalizing the Digital Personal Data Protection Act to safeguard citizens' digital rights.",
        "media.pr.2.date": "Mar 07, 2025",
        "media.pr.2.title": "Cabinet approves IndiaAI Mission with outlay of ₹10,372 crore",
        "media.pr.2.desc": "A significant step towards making AI in India and Making AI Work for India, democratizing access to computing resources for startups and researchers.",
        "media.pr.3.date": "Nov 05, 2025",
        "media.pr.3.title": "IndiaAI Governance Framework released for Ethical AI",
        "media.pr.3.desc": "MeitY unveils comprehensive guidelines to ensure safe, trusted, and inclusive AI adoption across healthcare, agriculture, and governance sectors.",
        "media.subscribe": "Subscribe to Updates",
        "media.sub_desc": "Get the latest government notifications directly to your inbox.",
        "media.email_ph": "Email Address",
        "media.btn_sub": "Subscribe",
        "contact.title": "Contact Us",
        "contact.subtitle": "We are here to help. Reach out to us for any queries or support.",
        "contact.office": "Head Office",
        "contact.helpline": "Helpline",
        "contact.hours": "Working Hours",
        "contact.address.line1": "Ministry of Electronics & IT,",
        "contact.address.line2": "Electronics Niketan, 6, CGO Complex,",
        "contact.address.line3": "Lodhi Road, New Delhi - 110003",
        "contact.phone.tollfree": "Toll Free: 1800-111-xxx",
        "contact.phone.support": "Support: +91-11-2345xxxx",
        "contact.hours.days": "Mon - Fri: 9:00 AM - 5:30 PM",
        "contact.hours.closed": "Closed on Gazetted Holidays",
        "contact.form.title": "Send us a Message",
        "contact.label.name": "Full Name",
        "contact.label.email": "Email Address",
        "contact.label.subject": "Subject",
        "contact.label.message": "Message",
        "contact.btn.send": "Send Message"
    },
    hi: {
        "header.title": "भारत सरकार",
        "header.subtitle": "इलेक्ट्रॉनिक्स और सूचना प्रौद्योगिकी मंत्रालय",
        "search.placeholder": "सेवाएं खोजें या आवेदन ट्रैक करें...",
        "home.hero.title": "सरकारी दस्तावेजों के लिए आवेदन करें",
        "home.hero.title.highlight.0": "पहले से कहीं ज्यादा तेज़",
        "home.hero.title.highlight.1": "बिना किसी कार्यालय जाए",
        "home.hero.title.highlight.2": "बिना कागजी कार्रवाई के",
        "home.hero.title.highlight.3": "AI की शक्ति के साथ",
        "home.hero.subtitle": "नागरिक सेवाओं के लिए आधिकारिक पोर्टल। अपने प्रमाण सुरक्षित रूप से अपलोड करें और AI को सरकारी कागजी कार्रवाई में आपकी सहायता करने दें।",
        "home.btn.start": "अभी आवेदन करें",
        "home.btn.learn": "यह कैसे काम करता है",
        "home.pill.0": "डिजिटल इंडिया पहल",
        "home.pill.1": "नागरिकों का सशक्तिकरण",
        "home.pill.2": "न्यूनतम सरकार, अधिकतम शासन",
        "home.pill.3": "कागज रहित, चेहरा रहित, नकद रहित",
        "home.feature.verify": "आधार सत्यापन",
        "home.feature.verify.desc": "यूआईडीएआई मानकों का उपयोग कर सुरक्षित पहचान प्रमाणीकरण।",
        "home.feature.autofill": "AI सहायक",
        "home.feature.autofill.desc": "कई भारतीय भाषाओं में वॉयस-सक्षम फॉर्म भरना।",
        "home.feature.instant": "डिजिलॉकर एकीकरण",
        "home.feature.instant.desc": "जारी किए गए दस्तावेज तुरंत आपके डिजिलॉकर में उपलब्ध हैं।",
        "home.select.title": "नागरिक सेवा चुनें",
        "home.select.subtitle": "वह मंत्रालय सेवा चुनें जिसके लिए आप आवेदन करना चाहते हैं।",
        "footer.about": "इस पोर्टल के बारे में",
        "footer.desc": "आर्टिफिशियल इंटेलिजेंस के माध्यम से नागरिक सेवाओं को सरल बनाने के लिए भारत सरकार की एक पहल।",
        "footer.links": "सरकारी लिंक",
        "footer.contact": "संपर्क विवरण",
        "footer.rights": "भारत सरकार। सर्वाधिकार सुरक्षित।",
        "upload.title": "आवश्यक दस्तावेज अपलोड करें",
        "upload.desc": "सत्यापन के लिए सुरक्षित रूप से प्रमाण अपलोड करें।",
        "upload.secure.title": "सुरक्षित अपलोड",
        "upload.secure.desc": "आपके दस्तावेज़ एन्क्रिप्टेड हैं और सुरक्षित रूप से संसाधित किए जाते हैं। आपकी सहमति के बिना कोई भी डेटा स्थायी रूप से संग्रहीत नहीं किया जाता है।",
        "upload.optional.title": "वैकल्पिक",
        "upload.optional.desc": "दस्तावेज़ अपलोड फ़ील्ड को ऑटो-भरने में मदद करते हैं, लेकिन यदि आप चाहें तो आप छोड़ सकते हैं और मैन्युअल प्रविष्टि के लिए आगे बढ़ सकते हैं।",
        "upload.doc.aadhaar": "आधार कार्ड",
        "upload.doc.pan": "पैन कार्ड",
        "upload.doc.income": "आय प्रमाण",
        "upload.instr.aadhaar": "दोनों तरफ (आगे और पीछे) या एक ही पीडीएफ अपलोड करें",
        "upload.instr.generic": "स्पष्ट छवि या पीडीएफ अपलोड करें",
        "upload.btn.back": "प्रारंभ करें",
        "upload.btn.skip": "छोड़ें और मैन्युअल रूप से भरें",
        "how.title": "यह कैसे काम करता है",
        "how.subtitle": "अपने सरकारी प्रमाण पत्र प्राप्त करने की सरल 4-चरणीय प्रक्रिया।",
        "how.step1.title": "दस्तावेज़ अपलोड करें",
        "how.step1.desc": "अपने आधार, पैन, या अन्य आवश्यक आईडी सुरक्षित रूप से अपलोड करें।",
        "how.step2.title": "AI निष्कर्षण",
        "how.step2.desc": "हमारा सिस्टम आपके दस्तावेजों से स्वचालित रूप से विवरण पढ़ता है।",
        "how.step3.title": "फॉर्म ऑटो-फिल",
        "how.step3.desc": "सटीकता के लिए पहले से भरे गए आवेदन पत्र की समीक्षा करें।",
        "how.step4.title": "तत्काल डाउनलोड",
        "how.step4.desc": "अपना डिजिटल हस्ताक्षरित प्रमाण पत्र तुरंत प्राप्त करें।",
        "step.1": "सेवा चुनें",
        "step.2": "दस्तावेज़ अपलोड करें",
        "step.3": "फॉर्म की समीक्षा करें",
        "step.4": "पूर्ण",
        "upload.drag": "दस्तावेज़ अपलोड करने के लिए क्लिक करें",
        "upload.drag.sub": "SVG, PNG, JPG या PDF (अधिकतम 10MB)",
        "upload.processing": "प्रोसेसिंग...",
        "upload.success": "फ़ाइल सफलतापूर्वक अपलोड की गई",
        "upload.instr.title": "महत्वपूर्ण निर्देश",
        "upload.instr.1": "विकल्प 1: दोनों तरफ (आगे और पीछे) के साथ एक दस्तावेज़ अपलोड करें।",
        "upload.instr.2": "विकल्प 2: 2 अलग-अलग फोटो (आगे और पीछे) अपलोड करें।",
        "upload.instr.generic.1": "सुनिश्चित करें कि पाठ स्पष्ट और पठनीय है।",
        "upload.instr.generic.2": "फ़ाइल का आकार 10MB से अधिक नहीं होना चाहिए।",
        "dashboard.title": "उपयोगकर्ता डैशबोर्ड",
        "dashboard.subtitle": "अपनी डिजिटल पहचान और दस्तावेजों को प्रबंधित करें।",
        "dashboard.signout": "साइन आउट",
        "dashboard.verified": "सत्यापित खाता",
        "dashboard.active_apps": "सक्रिय आवेदन",
        "dashboard.saved_fields": "सहेजे गए प्रोफ़ाइल फ़ील्ड",
        "dashboard.locker.title": "मेरा डिजिटल लॉकर",
        "dashboard.locker.subtitle": "दस्तावेजों से स्वचालित रूप से निकाला गया डेटा",
        "dashboard.field": "फ़ील्ड का नाम",
        "dashboard.value": "मान",
        "dashboard.source": "स्रोत",
        "dashboard.actions": "कार्रवाई",
        "dashboard.locker.empty": "अभी तक कोई डेटा संग्रहीत नहीं है। अपने लॉकर को स्वचालित रूप से भरने के लिए दस्तावेज़ अपलोड करें।",
        "dashboard.recent.title": "हाल की गतिविधि",
        "dashboard.recent.empty": "कोई हालिया आवेदन नहीं मिला। होम पेज पर एक नया आवेदन शुरू करें!",
        "dashboard.apply": "अभी आवेदन करें",
        "dashboard.delete.confirm": "क्या आप वाकई इस गतिविधि को हटाना चाहते हैं?",
        "dashboard.delete.fail": "आवेदन हटाने में विफल",
        "dashboard.update.fail": "प्रोफ़ाइल अपडेट करने में विफल",
        "in_progress": "प्रगति पर",
        "completed": "पूर्ण",
        "nav.dashboard": "डैशबोर्ड",
        "nav.profile": "प्रोफ़ाइल फ़ील्ड्स",
        "nav.applications": "आवेदन",
        "nav.home": "होम",
        "nav.about": "हमारे बारे में",
        "nav.login": "लॉग इन",
        "nav.register": "रजिस्टर",
        "nav.logout": "लॉग आउट",
        "nav.media": "मीडिया",
        "nav.contact": "संपर्क",
        "nav.projects": "परियोजनाएं",
        "nav.services": "सेवाएँ",
        "nav.settings": "सेटिंग्स",
        "about.title": "हमारे बारे में",
        "about.mission": "हमारा मिशन",
        "about.mission.desc": "नागरिकों को निर्बाध, पारदर्शी और कुशल डिजिटल सेवाएं प्रदान करके उन्हें सशक्त बनाना। हमारा लक्ष्य डिजिटल विभाजन को पाटना और यह सुनिश्चित करना है कि सरकारी लाभ अंतिम मील तक आसानी और गरिमा के साथ पहुंचें।",
        "about.vision": "दृष्टिकोण",
        "about.vision.desc": "डिजिटल पहुंच, समावेशन और सशक्तिकरण पर ध्यान केंद्रित करके भारत को एक डिजिटल रूप से सशक्त समाज और ज्ञान अर्थव्यवस्था में बदलना।",
        "about.values": "मूल्य",
        "about.value.1": "पारदर्शिता और अखंडता",
        "about.value.2": "नागरिक-केंद्रितता",
        "about.value.3": "नवाचार और उत्कृष्टता",
        "about.value.4": "समावेशिता",
        "about.who": "हम कौन हैं",
        "about.who.desc1": "इलेक्ट्रॉनिक्स और सूचना प्रौद्योगिकी मंत्रालय (MeitY) भारत के तकनीकी विकास के एक स्तंभ के रूप में खड़ा है। हम डिजिटल नवाचार, साइबर सुरक्षा और ई-गवर्नेंस के लिए एक संपन्न पारिस्थितिकी तंत्र को बढ़ावा देने के लिए प्रतिबद्ध हैं।",
        "about.who.desc2": "हमारा मंच प्रशासनिक प्रक्रियाओं को सुव्यवस्थित करने के लिए विभिन्न सेवाओं को एकीकृत करता है, कागजी कार्रवाई को कम करता है और प्रत्येक नागरिक के लिए जीवन की सुगमता को बढ़ाता है।",
        "services.title": "नागरिक सेवाएँ",
        "services.subtitle": "सभी के लिए सुलभ, पारदर्शी और कुशल सरकारी सेवाएँ।",
        "service.cert.title": "डिजिटल प्रमाण पत्र",
        "service.cert.desc": "जन्म, जाति, आय और अधिवास प्रमाण पत्र के लिए ऑनलाइन आवेदन करें।",
        "service.empl.title": "रोजगार कार्यालय",
        "service.empl.desc": "नौकरी के अवसरों और बेरोजगारी सहायता के लिए पंजीकरण करें।",
        "service.health.title": "स्वास्थ्य सेवाएँ",
        "service.health.desc": "टेलीमेडिसिन, अस्पताल नियुक्तियों और स्वास्थ्य रिकॉर्ड तक पहुँच प्राप्त करें।",
        "service.edu.title": "शिक्षा और छात्रवृत्ति",
        "service.edu.desc": "छात्रवृत्ति के लिए आवेदन करें और परीक्षा परिणाम देखें।",
        "service.land.title": "भूमि रिकॉर्ड",
        "service.land.desc": "भूमि स्वामित्व विवरण और संपत्ति के नक्शे देखें और सत्यापित करें।",
        "service.util.title": "बिल भुगतान",
        "service.util.desc": "बिजली, पानी और गैस बिलों का भुगतान निर्बाध रूप से करें।",
        "service.award.title": "पुरस्कार और सम्मान",
        "service.award.desc": "पद्म पुरस्कार और अन्य राज्य सम्मानों के लिए नामांकन।",
        "service.trans.title": "परिवहन सेवाएँ",
        "service.trans.desc": "लाइसेंस नवीनीकरण, वाहन पंजीकरण और चालान भुगतान।",
        "projects.title": "प्रमुख पहल",
        "projects.subtitle": "प्रमुख परियोजनाओं के माध्यम से राष्ट्र को बदलना।",
        "project.di.title": "डिजिटल इंडिया",
        "project.di.desc": "भारत को डिजिटल रूप से सशक्त समाज और ज्ञान अर्थव्यवस्था में बदलने के लिए एक प्रमुख कार्यक्रम।",
        "project.di.status": "चल रहा है",
        "project.sc.title": "स्मार्ट सिटी मिशन",
        "project.sc.desc": "स्मार्ट शहरों के विकास के लिए भारत सरकार द्वारा एक शहरी नवीनीकरण और रेट्रोफिटिंग कार्यक्रम।",
        "project.sc.status": "चरण 2",
        "project.bn.title": "भारतनेट",
        "project.bn.desc": "ऑप्टिकल फाइबर का उपयोग करके दुनिया का सबसे बड़ा ग्रामीण ब्रॉडबैंड कनेक्टिविटी कार्यक्रम।",
        "project.bn.status": "पूर्ण",
        "media.title": "मीडिया केंद्र",
        "media.latest": "नवीनतम प्रेस विज्ञप्ति",
        "media.gallery": "फोटो गैलरी",

        "media.view_all": "सभी तस्वीरें देखें",
        "media.pr.1.date": "14 नवंबर, 2025",
        "media.pr.1.title": "डिजिटल व्यक्तिगत डेटा संरक्षण नियम, 2025 अधिसूचित",
        "media.pr.1.desc": "भारत सरकार ने नागरिकों के डिजिटल अधिकारों की सुरक्षा के लिए, डिजिटल व्यक्तिगत डेटा संरक्षण अधिनियम को लागू करते हुए डीपीडीपी नियम 2025 को आधिकारिक तौर पर अधिसूचित किया है।",
        "media.pr.2.date": "07 मार्च, 2025",
        "media.pr.2.title": "कैबिनेट ने ₹10,372 करोड़ के परिव्यय के साथ IndiaAI मिशन को मंजूरी दी",
        "media.pr.2.desc": "भारत में AI और भारत के लिए AI को कार्यान्वित करने की दिशा में एक महत्वपूर्ण कदम, जो स्टार्टअप और शोधकर्ताओं के लिए कंप्यूटिंग संसाधनों तक पहुंच को लोकतांत्रिक बनाता है।",
        "media.pr.3.date": "05 नवंबर, 2025",
        "media.pr.3.title": "नैतिक AI के लिए IndiaAI गवर्नेंस फ्रेमवर्क जारी",
        "media.pr.3.desc": "MeitY ने स्वास्थ्य सेवा, कृषि और शासन क्षेत्रों में सुरक्षित, विश्वसनीय और समावेशी AI अपनाने को सुनिश्चित करने के लिए व्यापक दिशानिर्देशों का अनावरण किया।",
        "media.subscribe": "अपडेट के लिए सदस्यता लें",
        "media.sub_desc": "नवीनतम सरकारी सूचनाएं सीधे अपने इनबॉक्स में प्राप्त करें।",
        "media.email_ph": "ईमेल पता",
        "media.btn_sub": "सदस्यता लें",
        "contact.title": "संपर्क करें",
        "contact.subtitle": "हम मदद के लिए यहाँ हैं। किसी भी प्रश्न या सहायता के लिए हमसे संपर्क करें।",
        "contact.office": "प्रधान कार्यालय",
        "contact.helpline": "हेल्पलाइन",
        "contact.hours": "काम के घंटे",
        "contact.address.line1": "इलेक्ट्रॉनिक्स और सूचना प्रौद्योगिकी मंत्रालय,",
        "contact.address.line2": "इलेक्ट्रॉनिक्स निकेतन, 6, सीजीओ कॉम्प्लेक्स,",
        "contact.address.line3": "लोधी रोड, नई दिल्ली - 110003",
        "contact.phone.tollfree": "टोल फ्री: 1800-111-xxx",
        "contact.phone.support": "सहायता: +91-11-2345xxxx",
        "contact.hours.days": "सोम - शुक्र: सुबह 9:00 - शाम 5:30",
        "contact.hours.closed": "राजपत्रित अवकाश पर बंद",
        "contact.form.title": "हमें संदेश भेजें",
        "contact.label.name": "पूरा नाम",
        "contact.label.email": "ईमेल पता",
        "contact.label.subject": "विषय",
        "contact.label.message": "संदेश",
        "contact.btn.send": "संदेश भेजें"
    }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>("en");

    useEffect(() => {
        const stored = localStorage.getItem("app_lang") as Language;
        if (stored && (stored === "en" || stored === "hi")) {
            setLanguage(stored);
        }
    }, []);

    const toggleLanguage = () => {
        setLanguage((prev) => {
            const next = prev === "en" ? "hi" : "en";
            localStorage.setItem("app_lang", next);
            return next;
        });
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
